package com.osp.cts.model.queries;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 05 03:29:57 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesROVOImpl() {
    }

    /**
     * Returns the bind variable value for DeptId.
     * @return bind variable value for DeptId
     */
    public Number getDeptId() {
        return (Number) getNamedWhereClauseParam("DeptId");
    }

    /**
     * Sets <code>value</code> for bind variable DeptId.
     * @param value value to bind as DeptId
     */
    public void setDeptId(Number value) {
        setNamedWhereClauseParam("DeptId", value);
    }
}

