package com.osp.cts.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 05 03:04:24 CDT 2018
// ---------------------------------------------------------------------
public interface HrAppModule extends ApplicationModule {
    byte[] getHrReport(String deptId);
}

